### ISSUE TITLE
Añadir comunidades por medio de un communities.json

### ISSUE THREAD

**Issue by lcjury** [lcjury/comunidades-programacion-chile#2]
Seria ideal tener un archivo communities.json con el siguiente formato:
```json
{
   "noders": {
     "twitter": "https://twitter.com/nodersjs",
    ...
  },
 "otra comunidad": {
   ...
 }
}
```

y extender el task `build` de gulp para que inyecte el html de cada comunidad utilizando esté archivo. De esa forma, quien quiera añadir o modificar información no necesita tocar el HTML y basta con modificar el .json

**Comment by luchosrock** [comment]
Y un archivo en markdown? Así sería legible desde el sitio web o al visitar el repo

**Comment by lcjury** [comment]
Hoy en día cada comunidad solo consiste de un nombre y links a redes sociales, en verdad no habría nada que mirar en el markdown y habría que buscar algún paquete que soporte markdown con meta-data

**Comment by joseglego** [comment]
Yo pensé en que se podía hacer con otra herramienta. Pero seguí tu consejo y lo hice con gulp inject en: #3

**Comment by lcjury** [comment]
Muchas gracias por el PR joseglego, está buenisimo :D
